### PR TITLE
Remove 'omitted' feature

### PR DESCRIPTION
**Pull request by spkrka**

### CODE REVIEW

**Comment by krka** [comment]
@pettermahlen @liljencrantz @mattnworb

**Comment by pettermahlen** [comment]
Remind me what this feature does before the removal?

**Comment by spkrka** [comment]
This tried to figure which dependency artifacts existed in multiple versions or were left out for some reason. This isn't really needed since we can simply look at the things that are packaged. I thought this would help reduce false positives, but it turns out there are quite a lot of left out artifacts in practice.

**Comment by mattnworb** [comment]
a belated :+1:

**Pull request merged**
