### PR TITLE
remove guava deps from core

### PR DESCRIPTION
**Pull request by jto**

### CODE REVIEW

**Comment by jto** [comment]
Seems like travis is broken :(

**Comment by mattnworb** [comment]
Actually guava is used in https://github.com/spotify/missinglink/blob/master/core/src/main/java/com/spotify/missinglink/datamodel/MethodDescriptors.java and other classes in the package. We should probably remove that usage, but I'm gonna revert this until then.

**Comment by jto** [comment]
There's something super fishy. The code should have failed to compile.

**Comment by mattnworb** [comment]
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ missinglink-core ---
[INFO] com.spotify:missinglink-core:jar:0.1.5-SNAPSHOT
[INFO] +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] +- org.ow2.asm:asm-tree:jar:7.1:compile
[INFO] |  \- org.ow2.asm:asm:jar:7.1:compile
[INFO] +- io.norberg:auto-matter:jar:0.11.0:provided
[INFO] |  +- io.norberg:auto-matter-annotation:jar:0.11.0:provided
[INFO] |  +- com.squareup:javapoet:jar:1.0.0:provided
[INFO] |  +- com.google.guava:guava:jar:18.0:provided
[INFO] |  \- org.modeshape:modeshape-common:jar:3.8.1.Final:provided
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] \- org.assertj:assertj-core:jar:1.7.1:test
```

**Comment by mattnworb** [comment]
I created #56 to track getting rid of it (and fixing the auto-matter weirdness)

**Pull request merged**
