### PR TITLE
Make plugin work on java11

### PR DESCRIPTION
**Pull request by OskarKjellin**

### CODE REVIEW

**Comment by mattnworb** [comment]
Nice, thanks! Do you think it is worth adding an entry to the Travis CI config to build/run on Java 11 in CI too, for verification?

**Comment by OskarKjellin** [comment]
@mattnworb That sounds like a good idea! I tried it myself with java11, but have no idea how to do it on Travis CI

**Comment by mattnworb** [comment]
I believe you just add an entry here:

https://github.com/spotify/missinglink/blob/fd349fe49ccfbc00aeb6fc59504a4d77c759d660/.travis.yml#L9

https://docs.travis-ci.com/user/languages/java/#using-java-10-and-later

**Comment by mattnworb** [comment]
thanks again! I'll cut a release.

**Comment by OskarKjellin** [comment]
Cool, thanks for reviewing and fixing the release!

**Comment by mattnworb** [comment]
released `0.1.2`

**Pull request merged**
